In [2]:
!python --version

Python 3.11.4


### Building GPT

In [3]:
# We always start with a dataset to train on. Let's download the tiny shakespeare dataset
#!wget https://raw.githubusercontent.com/karpathy/char-rnn/master/data/tinyshakespeare/input.txt

In [4]:
# reading text data

with open('input.txt', 'r', encoding='utf-8') as f:
    text = f.read()

In [5]:
print("length of dataset in characters: ", len(text))

length of dataset in characters:  1115394


In [6]:
# let's look at the first 1000 characters
print(text[:1000])

First Citizen:
Before we proceed any further, hear me speak.

All:
Speak, speak.

First Citizen:
You are all resolved rather to die than to famish?

All:
Resolved. resolved.

First Citizen:
First, you know Caius Marcius is chief enemy to the people.

All:
We know't, we know't.

First Citizen:
Let us kill him, and we'll have corn at our own price.
Is't a verdict?

All:
No more talking on't; let it be done: away, away!

Second Citizen:
One word, good citizens.

First Citizen:
We are accounted poor citizens, the patricians good.
What authority surfeits on would relieve us: if they
would yield us but the superfluity, while it were
wholesome, we might guess they relieved us humanely;
but they think we are too dear: the leanness that
afflicts us, the object of our misery, is as an
inventory to particularise their abundance; our
sufferance is a gain to them Let us revenge this with
our pikes, ere we become rakes: for the gods know I
speak this in hunger for bread, not in thirst for revenge.



In [7]:
# here are all the unique characters that occur in this text
# these are the possible characters the model can see or emit

chars = sorted(list(set(text)))
vocab_size = len(chars)
print(''.join(chars))
print(vocab_size)


 !$&',-.3:;?ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz
65


In [8]:
# create a mapping from characters to integers
stoi = { ch:i for i,ch in enumerate(chars)} # creating a lookup table char to integer
itos = { i:ch for i,ch in enumerate(chars)} # creating a lookup table ineger to char
encode = lambda s: [stoi[c] for c in s ] # encoder: take a string, output a list of integers
decode = lambda l: ''.join([itos[i] for i in l]) # decoder: take a list of intergers, output a string

'''
in our experiment we are using character level tokenizer.
we only have 65 vocab. so, our integer sequence length will be big/long
'''

print(encode('hi there'))
print(decode(encode('hi there')))

[46, 47, 1, 58, 46, 43, 56, 43]
hi there


#### Let's now encode the entire text of dataset and store it into a torch.Tensor

In [9]:
import torch

data = torch.tensor(encode(text), dtype=torch.long)
print(data.shape, data.dtype)
print(data[:1000]) # the 1000 characters we looked at earlier will to the GPT look like this

torch.Size([1115394]) torch.int64
tensor([18, 47, 56, 57, 58,  1, 15, 47, 58, 47, 64, 43, 52, 10,  0, 14, 43, 44,
        53, 56, 43,  1, 61, 43,  1, 54, 56, 53, 41, 43, 43, 42,  1, 39, 52, 63,
         1, 44, 59, 56, 58, 46, 43, 56,  6,  1, 46, 43, 39, 56,  1, 51, 43,  1,
        57, 54, 43, 39, 49,  8,  0,  0, 13, 50, 50, 10,  0, 31, 54, 43, 39, 49,
         6,  1, 57, 54, 43, 39, 49,  8,  0,  0, 18, 47, 56, 57, 58,  1, 15, 47,
        58, 47, 64, 43, 52, 10,  0, 37, 53, 59,  1, 39, 56, 43,  1, 39, 50, 50,
         1, 56, 43, 57, 53, 50, 60, 43, 42,  1, 56, 39, 58, 46, 43, 56,  1, 58,
        53,  1, 42, 47, 43,  1, 58, 46, 39, 52,  1, 58, 53,  1, 44, 39, 51, 47,
        57, 46, 12,  0,  0, 13, 50, 50, 10,  0, 30, 43, 57, 53, 50, 60, 43, 42,
         8,  1, 56, 43, 57, 53, 50, 60, 43, 42,  8,  0,  0, 18, 47, 56, 57, 58,
         1, 15, 47, 58, 47, 64, 43, 52, 10,  0, 18, 47, 56, 57, 58,  6,  1, 63,
        53, 59,  1, 49, 52, 53, 61,  1, 15, 39, 47, 59, 57,  1, 25, 39, 56, 41,
      

/var/folders/gn/2x1vvpwj6qzbnf9ntmrq2h5r0000gn/T/ipykernel_4937/699030071.py:3: UserWarning: Failed to initialize NumPy: No module named 'numpy' (Triggered internally at /Users/runner/work/pytorch/pytorch/pytorch/torch/csrc/utils/tensor_numpy.cpp:84.)
  data = torch.tensor(encode(text), dtype=torch.long)


### Split up the data into train and validation sets

In [10]:
n = int(0.9*len(data))

train_data = data[:n] # first 90% will be train and rest validation data
val_data = data[n:]

'''
    so, this will help us understand to what extent our model is overfitting.
    we don't want exact memorization of the exact shakespeare.
    we want nn that creates shakespeare like text
'''

"\n    so, this will help us understand to what extent our model is overfitting.\n    we don't want exact memorization of the exact shakespeare.\n    we want nn that creates shakespeare like text\n"

### Time Dimension of the tensors that are going to be feeding into the transformers

In [11]:
'''
    Training a transformer on entire dataset is computationally expensive.
    So, we will train the model based on chunks/batches (random sample of the datasets).
    These chunks have some maximum length.
    there are some other names context_length or block size.
    Here, we will call as a block size
'''

block_size = 8
train_data[:block_size+1]

tensor([18, 47, 56, 57, 58,  1, 15, 47, 58])

##### the above output means:
                - In the context of 18, 47 likely comes next
                - In the context of 18, 47, the integer 56 will come next
                like wise .....

In [12]:
x = train_data[:block_size] # input to the transformers, just the block size of characters
y = train_data[1:block_size+1] # will be the next block size characters. so, basically it means offset by one.
                                # because y are the targets for each position in the input
for t in range(block_size):
    context = x[:t+1]
    target = y[t]
    print(f"when input is {context} the target: {target}")

when input is tensor([18]) the target: 47
when input is tensor([18, 47]) the target: 56
when input is tensor([18, 47, 56]) the target: 57
when input is tensor([18, 47, 56, 57]) the target: 58
when input is tensor([18, 47, 56, 57, 58]) the target: 1
when input is tensor([18, 47, 56, 57, 58,  1]) the target: 15
when input is tensor([18, 47, 56, 57, 58,  1, 15]) the target: 47
when input is tensor([18, 47, 56, 57, 58,  1, 15, 47]) the target: 58


#### Observations:

    - above are the 8 examples hidden in the chunk of nine characters that we sampled from the training set
    chunk - tensor([18, 47, 56, 57, 58,  1, 15, 47, 58])
    - we train all the examples with context between one all the way up to context of block size
    - we did this way not only because of computationally expensive. But,
    - we want the Transformer network be used to seeing contexts all the way from as little as one all the way to block size
    - And we'd like the tranformer to be used to seeing everthing in between
        - that's going to be useful later during inference.
        - Because, while we're sampling we can start the sampling generation with as little as one character of context
        - And, the tranformers know how to predict the next character with all the way up to just one context one and so
        - then it can predict everything up to block size and after block size we have to start truncating because the Transformers
          will never receive more than the block size inputs when it's predicting the next character

#### Batch Dimension

In [13]:
torch.manual_seed(1337) # sampling random locations in the dataset to pull chunks from, here we are setting the seed in the random number generator to get determinstic output all the time
batch_size = 4 # how many independent sequences will be process (in every forward and backward pass) in parallel?
block_size = 8 # what is the maximum context length for predictions

def get_batch(split):
    '''generate a small batch of data of inputs x and targets y
    '''
    
    data = train_data if split == 'train' else val_data # if split equal to train will look into train or else val_data
    '''
    ix descriptions:
        when I generate random positions to grab a chuk out of data.
        I actually, generate batch size number of random offsets.
        ex: so, batch_size = 4, so ix going to be a 4 numbers that are randomly generated between 0 and len(data)-block_size
    '''
    ix = torch.randint(len(data) - block_size, (batch_size, )) # it's just the random offsets in the training set
    x = torch.stack([data[i:i+block_size] for i in ix]) # first block size characters starting at i the y's are the offset by one of that
    y = torch.stack([data[i+1:i+block_size+1] for i in ix])

    return x,y


xb, yb = get_batch('train')
print('inputs:')
print(xb.shape) # 4x8 matrix, 4 batche_size, 8 - each block size
print(xb)
print('targets:')
print(yb.shape)
print(yb)


print('----------')

for b in range(batch_size): # batch dimension
    for t in range(block_size): # time dimension
        context = xb[b, :t+1]
        target = yb[b,t]
        print(f'when the input is {context.tolist()} the target: {target}')


inputs:
torch.Size([4, 8])
tensor([[24, 43, 58,  5, 57,  1, 46, 43],
        [44, 53, 56,  1, 58, 46, 39, 58],
        [52, 58,  1, 58, 46, 39, 58,  1],
        [25, 17, 27, 10,  0, 21,  1, 54]])
targets:
torch.Size([4, 8])
tensor([[43, 58,  5, 57,  1, 46, 43, 39],
        [53, 56,  1, 58, 46, 39, 58,  1],
        [58,  1, 58, 46, 39, 58,  1, 46],
        [17, 27, 10,  0, 21,  1, 54, 39]])
----------
when the input is [24] the target: 43
when the input is [24, 43] the target: 58
when the input is [24, 43, 58] the target: 5
when the input is [24, 43, 58, 5] the target: 57
when the input is [24, 43, 58, 5, 57] the target: 1
when the input is [24, 43, 58, 5, 57, 1] the target: 46
when the input is [24, 43, 58, 5, 57, 1, 46] the target: 43
when the input is [24, 43, 58, 5, 57, 1, 46, 43] the target: 39
when the input is [44] the target: 53
when the input is [44, 53] the target: 56
when the input is [44, 53, 56] the target: 1
when the input is [44, 53, 56, 1] the target: 58
when the input i

#### Observations:
    - this 4x8 array contains a completely independent as far as the Transformer is concerned
    - These are 32 independet examples packed into a single batch of the input x and the desired targets y

In [14]:
print(xb) # our input to the tranformer

tensor([[24, 43, 58,  5, 57,  1, 46, 43],
        [44, 53, 56,  1, 58, 46, 39, 58],
        [52, 58,  1, 58, 46, 39, 58,  1],
        [25, 17, 27, 10,  0, 21,  1, 54]])


### BigramLanguageModel

In [51]:
import torch
import torch.nn as nn
from torch.nn import functional as F
torch.manual_seed(1337)

class BigramLanguageModel(nn.Module):

    def __init__(self, vocab_size) -> None:
        super().__init__()
        # each token directly reads off the logits for the next token from a lookup table
        self.token_embedding_table = nn.Embedding(vocab_size, vocab_size) # nn.Embedding is a very thin wrapper, basically a tensor of shape vocab_size x vocab_size 

    def forward(self, idx, targets=None):

        #idx and targets are both (B,T) tensor of integers
        ''' 
        idx: tensor of integers
        targets: target tensor of integers

        self.token_embedding_table(idx): when we pass index ([[24, 43, 58,  5, 57,  1, 46, 43]]) here,
                                         every single integer in our index is going to refer this embedding table and pluck out the row of that embedding table corresponding to that index.
                                         eg: index 24 will go into the embedding table and pluck out the 24th row,
                                         this 24th row has a scores for the next character in the sequence.
        logits: (B,T,C), 4 x 8 x 65
        are basically the scores for the next character in the sequence
        '''
        
        logits = self.token_embedding_table(idx) # (B,T,C), B - Batch (4), T - Time (8), C - Channel (vocab_size) (65)
        # thru logits we've made predictions about what comes next
        # and now we'd like to evaluate the loss functions
        # a good way to measure a loss or quality of predictions is to use the negative log likelihood loss in pytorch it is referred as cross_entropy

        # predicted (logits) and true values (targets)

        # usually cross_entropy from pytorch expects the input in (B,C,T) But we have B,T,C
        if targets is None:
            loss = None
        else:
            B, T, C = logits.shape
            logits = logits.view(B*T, C)
            targets = targets.view(B*T)
            loss = F.cross_entropy(logits, targets) 

        return logits, loss

    def generate(self, idx, max_new_tokens):
        ''' This function will take idx (B, T) array of indices in the current context
            and generate B by T+1, T+2 or T+3 as many as we want maximum tokens.
            So, this is generation from the model.

            This generate will operate based on batches.

        Arguments:
            idx: This is the current context of some characters in a batch/some batch
            max_new_tokens: max no.of T+1 characters
        '''
        for _ in range(max_new_tokens):
            # get the predictions
            # here we are not using the loss, as we don't have any ground truth targets, it's getting ignored
            logits, loss = self(idx)
            #print(f'logits before tranformations = {logits} and shape = {logits.shape}')

            # focus only on the last time step, we are plucking out the last char/digit in the time dimension(-1) because that last char/digit is the prediction
            logits = logits[:, -1, :] # becomes (B,C)
            #print(f'logits after tranformations = {logits} and shape = {logits.shape}')
            # apply softmax to get probabilities
            probs = F.softmax(logits, dim=-1) # (B,C)
            #print(f'probs = {probs}')
            # sample from the distribution
            idx_next = torch.multinomial(probs, num_samples=1) # (B, 1)
            #print(f'idx_next = {idx_next}')
            # append sampled index to the running sequence
            idx = torch.cat((idx, idx_next), dim=1) # (B, T+1)
        return idx


m = BigramLanguageModel(vocab_size)
#tst_x = torch.tensor([[24, 43, 58,  5, 57,  1, 46, 43]])
#tst_y = torch.tensor([[43, 58,  5, 57,  1, 46, 43, 39]])
logits, loss = m(xb, yb)
print(logits.shape)
print(loss)

# here 1x1 tensor which is of zeros, in our encoding zero represents new line
print('The generation we achieved')
idx = torch.zeros((1,1), dtype=torch.long)
print(f'idx = {idx}')
print(decode(m.generate(idx, max_new_tokens=100)[0].tolist()))



torch.Size([256, 65])
tensor(4.7108, grad_fn=<NllLossBackward0>)
The generation we achieved
idx = tensor([[0]])

SKIcLT;AcELMoTbvZv C?nq-QE33:CJqkOKH-q;:la!oiywkHjgChzbQ?u!3bLIgwevmyFJGUGp
wnYWmnxKWWev-tDqXErVKLgJ


#### Observations:

    - when we do -ln(1/65) = 4.174. But, we got the loss as 4.8786
    - So, our inital predictions are not super diffuse, we got little bit of entropy. so, we're guessing wrong
    - But, now we are evaluate the loss

#### Create a PyTorch optimizer

In [39]:
optimizer = torch.optim.AdamW(m.parameters(), lr=1e-3)

In [54]:
batch_size = 32

for steps in range(10000):

    # sample a batch of data
    xb, yb = get_batch('train')

    # evaluate the loss
    logits, loss = m(xb, yb)
    # zeroing out all the gradients from previous step and getting
    optimizer.zero_grad(set_to_none=True)
    # getting the gradients for all the parameters
    loss.backward()
    # and using those gradients to update their parameters
    optimizer.step()

print(loss.item())


4.684566974639893


In [55]:
print(decode(m.generate(idx = torch.zeros((1,1), dtype=torch.long), max_new_tokens=500)[0].tolist()))


pm foglO:p?Gbz'jbO:CKHxmhsEWe,rEq f jnQw'YGnYW:VJiKu CKb$vZbjgjQMV&qVTQlgnENs$.?O U'yjyff?h
'zxZnWtKpgu3KpoiPFhix
SJ'
yFjjN3Q&u3WgMmywW$GJL?sPY?YtNpErgIo,XcJ&DniqVmZBwfFD3faBoi'I3Q?$xBr&G,yxUN!Wsyy cLC-IBothTsze'W?q;!:xrFti.ZQyJyQ!u!zHK$EQq-wM.T'QUiN.SPyjKtL&vbRwW,SZBCj?aUIUxDALpAUGFbLQXNVY.sBId-'wNm;UL:3Sq-KAiqRiN:lL-Qm,iCulyZUAP,oSB3SlriFWiy;GJ,NuUxxTER-!a!UYN
kOpJU'usc UIo.JAa!U CjuRw'TthF;aLq-KX&jzCE;HzE-Wla!uDKBjuxVBk!UQXlFlaXt,wWWV&G;HU?zW:.ObX?wfRkRyJBUzK$Evi
hjdlgGrT?I33StKa;AUGJAE-WWgI'


#### Mathematical trick in self-attention

In [57]:
# toy example

torch.manual_seed(1337)
'''Here, we've up to 8 tokens in a batch.
   currently, these 8 tokens are not talking to each other.
   we would like to talk to each other/ couple them each other
   and in particular, the token at 5th location should not communicate at token at 6th, 7th ...
   because those are the future tokens in a sequence.
   so, the token on the 5th location should only talk to the one in the 4th, 3rd, 2nd, 1st
   Information only flows from previous context to the current timestep
'''
B,T,C = 4,8,2 # batch, time, channel

x = torch.randn(B, T, C)
x.shape

torch.Size([4, 8, 2])

In [59]:
'''Now, if I want my tokens to talk each other the simplest way is to 
   average the all the previous channels, information at my step but then also the
   channels from the four step, third, 2 and 1.
   I'd like to average those up and then it becomes the feature vector that summarizes me in the context of my history.
   weak form of interaction: an average is extremely weak form of interaction, we've lost the ton of information on spatial arrangements of
                             all those tokens but that's ok for now
'''

"Now, if I want my tokens to talk each other the simplest way is to \n   average the all the previous channels, information at my step but then also the\n   channels from the four step, third, 2 and 1.\n   I'd like to average those up and then it becomes the feature vector that summarizes me in the context of my history.\n   weak form of interaction: an average is extremely weak form of interaction, we've lost the ton of information on spatial arrangements of\n                             all those tokens but that's ok for now\n"

In [60]:
# we want x[b,t] = mean_{i<=t} x[b,i]
xbow = torch.zeros((B,T,C))
for b in range(B):
    for t in range(T):
        xprev = x[b, :t+1] # (t,c)
        xbow[b,t] = torch.mean(xprev, 0)